# Generated by Django 3.2.16 on 2024-03-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=255)),
            ],
        ),
    ]
